/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialog;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sicat.DBConnect;

/**
 *
 * @author chris
 */
public class dlgTambahEditPengeluaranKas extends javax.swing.JDialog {

    /**
     * Creates new form dlgTambahEditPengeluaranKas
     */
    static int tipe = 0;
    static int tipepeng = 0;
    static int id = 0;
    public dlgTambahEditPengeluaranKas(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
        try {
            insertKodePer();
        } catch (SQLException ex) {
            Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(tipe==0){
            jLabel4.setText("Tambah Data");
            jButton1.setText("Tambah Data");
        } else {
            jLabel4.setText("Edit Data");
            jButton1.setText("Edit Data");
        }
    }

    public dlgTambahEditPengeluaranKas(java.awt.Frame parent, boolean modal,int tipe, int tipepeng, int id) {
        super(parent, modal);
        initComponents();
        this.id = id;
        this.tipe = tipe;
        this.tipepeng = tipepeng;
        try {
            insertKodePer();
            insertNama();
        } catch (SQLException ex) {
            Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(tipe==0){
            jLabel4.setText("Tambah Data");
            jButton1.setText("Tambah Data");
        } else {
            jLabel4.setText("Edit Data");
            jButton1.setText("Edit Data");
            try {
                insertEdit();
            } catch (SQLException ex) {
                Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void insertKodePer() throws SQLException{
        String SQL = "SELECT * FROM kodeperkiraan";
        jComboBox1.removeAllItems();
        ResultSet rs = DBConnect.executeQuery(SQL);
        while(rs.next()){
            jComboBox1.addItem(rs.getString("namaPer"));
        }
    }
    
    private void insertNama() throws SQLException{
        String SQL = "SELECT * FROM nama2";
        jComboBox2.removeAllItems();
        ResultSet rs = DBConnect.executeQuery(SQL);
        while(rs.next()){
            jComboBox2.addItem(rs.getString("nama"));
        }
    }
    
    private void insertEdit() throws SQLException{
        String SQL = "SELECT * FROM pengeluarankas "
                + "INNER JOIN nama2 ON pengeluarankas.namaId = nama2.namaId "
                + "INNER JOIN kodeperkiraan ON pengeluarankas.kodePer = kodeperkiraan.kodePer "
                + "WHERE id = '"+id+"'";
        ResultSet rs = DBConnect.executeQuery(SQL);
        if(rs.next()){
            jComboBox2.setSelectedItem(rs.getString("nama"));
            jDateChooser1.setDate(rs.getDate("tgl"));
            jComboBox1.setSelectedItem(rs.getString("namaPer"));
            jTextField1.setText(rs.getString("namaPegawai"));
            jTextField2.setText(rs.getString("debet"));
            jTextField3.setText(rs.getString("kredit"));
            jTextArea1.setText(rs.getString("description"));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tanggal");

        jLabel2.setText("Kode Perkiraan");

        jLabel3.setText("Nama Pegawai");

        jLabel4.setText("jLabel4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Debet");

        jLabel6.setText("Rp.");

        jLabel7.setText("Kredit");

        jLabel8.setText("Rp.");

        jLabel9.setText("Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nama");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2))
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = jComboBox2.getSelectedItem().toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = sdf.format(jDateChooser1.getDate());
        String kodeper = jComboBox1.getSelectedItem().toString();
        String nampeg = jTextField1.getText().toString();
        String deb = jTextField2.getText().toString();
        String kred = jTextField3.getText().toString();
        String desc = jTextArea1.getText().toString();
        String namaid = "";
        String kodeperk = "";
        if(tgl == null||kodeper == null||nampeg.isEmpty()||deb.isEmpty()||kred.isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap lengkapi data terlebih dahulu",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } if(tipe ==0){
            try {
                int tipepen = 1;
                if(tipepeng == 1){
                    tipepen = 2;
                }
                String SQL0 = "SELECT kodePer FROM kodeperkiraan WHERE namaPer = '"+kodeper+"'";
                ResultSet rs2 = DBConnect.executeQuery(SQL0);
                if(rs2.next()){
                    kodeperk = rs2.getString("kodePer");
                    String SQL = "SELECT namaId FROM nama2 WHERE nama = '"+nama+"'";
                    ResultSet rs = DBConnect.executeQuery(SQL);
                    if(rs.next()){
                        namaid = rs.getString("namaId");
                        String SQL2 = "INSERT INTO pengeluarankas "
                                + "(tgl,kodePer,namaPegawai,description,debet,kredit,tipeId,namaId) "
                                + "VALUES('"+tgl+"','"+kodeperk+"','"+nampeg+"','"+desc+"','"+deb+"',"
                                + "'"+kred+"','"+tipepen+"','"+namaid+"')";
                        int status = DBConnect.execute(SQL2);
                        if(status == 1){
                            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Berhasil",
                                    JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Error",
                                    JOptionPane.WARNING_MESSAGE);
                        }
                        
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            String SQL1 = "SELECT kodePer FROM kodeperkiraan WHERE namaper = '"+kodeper+"'";
            String kodePer = "";
            ResultSet rs2 = DBConnect.executeQuery(SQL1);
            try {
                if(rs2.next()){
                    kodePer = rs2.getString("kodePer");
                    String SQL2 = "SELECT namaId from nama2 WHERE nama = '"+nama+"'";
                    String namaId ="";
                    ResultSet rs = DBConnect.executeQuery(SQL2);
                    if (rs.next()){
                        namaId = rs.getString("namaId");
                        String SQL3 = "UPDATE pengeluarankas SET tgl = '"+tgl+"', "
                                + "kodePer = '"+kodePer+"', "
                                + "namaPegawai = '"+nampeg+"', "
                                + "description = '"+desc+"', "
                                + "debet = '"+deb+"', "
                                + "kredit = '"+kred+"', "
                                + "namaId = '"+namaId+"' "
                                + "WHERE id = '"+this.id+"'";
                        int status = DBConnect.execute(SQL3);
                        if(status == 1){
                            JOptionPane.showMessageDialog(this, "Data berhasil dirubah","Berhasil",
                                    JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Data gagal dirubah","Error",
                                    JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgTambahEditPengeluaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgTambahEditPengeluaranKas dialog = new dlgTambahEditPengeluaranKas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
